### ISSUE TITLE
Compiling the Engine/Systems

### ISSUE THREAD

**Issue by ookami125** [StrellyN/WishEngine#1]
So I was going to look over the engine out of interest but it seems you didn't include a way to compile the anything. Is there any plans to include a make, cmake or visual studio solution?

**Comment by StrellyN** [comment]
Sure thing, I'll look into it and update it as soons as I can. Thanks and sorry for the inconvinience.

**Comment by ookami125** [comment]
It's all good, and thanks for the quick reply.

**Comment by StrellyN** [comment]
CMakeList added and tested on linux, tests on windows comming soon, but I'm gonna close the issue now, thank you for issuing it!
